/**
 * 客户的常规设置
 * CUSTOMER_REGIMEN_NORMAL 普通增值税
 * CUSTOMER_CALIFICACION_NORMAL 应税非免税
 */
export const CustomerNormalEnum = {
  CUSTOMER_REGIMEN_NORMAL: '01',
  CUSTOMER_CALIFICACION_NORMAL: 'S1',
}

/**
 * 客户类型
 * CUSTOMER_REGIMEN_NORMAL 普通增值税
 * CUSTOMER_REGIMEN_RE 个体户附加税

 */
export const CustomerRegimenEnum = {
  CUSTOMER_REGIMEN_NORMAL: '01',
  CUSTOMER_REGIMEN_RE: '18',
}

/**
 * 客户资质
 * CUSTOMER_CALIFICACION_NORMAL 应税非免税
 * CUSTOMER_CALIFICACION_TAX_FREE 应税免税(医疗/教育)
 * CUSTOMER_CALIFICACION_EUROPEAN 欧盟内部交易(免税)
 * CUSTOMER_CALIFICACION_INTERNATIONAL 国际出口(免税)
 * CUSTOMER_CALIFICACION_OTHER 其他免税情况
 */
export const CustomerCalificacionEnum = {
  CUSTOMER_CALIFICACION_NORMAL: 'S1',
  CUSTOMER_CALIFICACION_TAX_FREE: 'S2',
  CUSTOMER_CALIFICACION_EUROPEAN: 'E1',
  CUSTOMER_CALIFICACION_INTERNATIONAL: 'E2',
  CUSTOMER_CALIFICACION_OTHER: 'E3',
}